apiVersion: core.cnrm.cloud.google.com/v1beta1
kind: ConfigConnector
metadata:
  name: configconnector.core.cnrm.cloud.google.com
spec:
  googleServiceAccount: "cnrmsadev-cluster@ejmadkins-anthos-demo.iam.gserviceaccount.com" 
  mode: cluster
